# Generated by Django 5.2 on 2025-04-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('provider', 'Provider'), ('admin', 'admin')], default='restaurant', max_length=20),
        ),
    ]
